development:
  adapter: postgresql
  database: yatl_development
  pool: 5
  timeout: 5000
  encoding: unicode

test:
  adapter: postgresql
  database: yatl_test
  pool: 5
  timeout: 5000
  encoding: unicode

staging:
  adapter: postgresql
  database: yatl_staging
  pool: 5
  timeout: 5000
  encoding: unicode

production:
  adapter: postgresql
  database: yatl_production
  pool: 5
  timeout: 5000
  encoding: unicode
